apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website-deployment
spec:
  replicas: 3  # Number of replicas for redundancy and scaling
  selector:
    matchLabels:
      app: my-website-1
  template:
    metadata:
      labels:
        app: my-website-1
    spec:
      containers:
      - name: my-website-container
        image: anupkrishna2000/myphpexam:v2
        ports:
        - containerPort: 80 